---
- name: Setup containers with Nginx
  hosts: all
  become: yes

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Enable and Start Nginx
      service:
        name: nginx
        state: started
        enabled: yes
